### ISSUE TITLE
Unable to assign multiple domains.

### ISSUE THREAD

**Issue by p4arth** [lkaesberg/EmailBot#1]
Hey! The bot is really helpful, but there is one issue we are facing, when we try to assign multiple domain names to the bot, I think it considers them all as a single one.

**Comment by lkaesberg** [comment]
Yes, I found the issue and resolved it.

**Comment by lkaesberg** [comment]
Please let me know if it works for you.

**Comment by p4arth** [comment]
yep! It works. now, Thank you so much.
