### ISSUE TITLE
New translation 

### ISSUE THREAD

**Issue by Norma1Name** [lkaesberg/EmailBot#6]
Hello, this is my translation to : Hebrew.
As an Israeli, Hebrew is my main language so I know it since I was born.
Here is the translation from the template file :

```
{
  "mailPositive": "אנא הזן את הקוד שנשלח אליך אל כתובת המעיל %VAR% (במידה ואינו מופיע יש לבדוק את הספאם, יכול להיות שזה מופיע שם).",
  "mailNegative": "לא ניתן לשלוח מייל אל כתובת המייל %VAR%",
  "roleAdded": "הרול נוסף אל %VAR%",
  "mailInvalid": "אנא כתבו כתובת מייל תקינה",
  "mailTimeout": "אנא חכו %VAR% שניות לפני שליחה מחדש של המייל",
  "invalidPermissions": "אין לך גישה להריץ את פקודה זו!",
  "commandFailed": "איראה שגיאה במהלך ביצוע פקודה זו!",
  "userRetry": "קרתה תקלה. אנא מחק והוסף מחדש את הריאקשן ונסה שוב.",
  "userBotError": "הבוט לא הוגדר כמו שצריך. אנא פנה לאדמין!",
  "userEnterEmail": "אנא כתוב את כתובת המייל שלך כדי לבצע אימות %VAR%.",
  "userCantFindRole": "הרולים לא נמצאו. אנא פנה לאדמין או איש צוות! עזרה: וודאו שהשם של הרול אותו הדבר והרול של הבוט גבוהה יותר מהרול של משתמש מאומת ומשתמש לא מאומת."
}
```

Hopefully you will add it soon!

**Comment by lkaesberg** [comment]
First of all, thanks a lot for your work. I added it, and it can be activated, but it looks kinda broken.
![image](https://user-images.githubusercontent.com/33939116/166830485-276b8496-2942-4947-b799-2673c4b04652.png)
The greater and less symbols are at strange positions, at least for my understanding^^

**Comment by Norma1Name** [comment]
Thank you for adding it. It's looks weird because it's Hebrew, and sometimes looks weird.
I'm sorry to you that you was needed to change the place of some functions.
